// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.1
// source: main.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Module_OnLoad_FullMethodName    = "/proto.Module/OnLoad"
	Module_OnUnload_FullMethodName  = "/proto.Module/OnUnload"
	Module_OnMessage_FullMethodName = "/proto.Module/OnMessage"
	Module_OnImcCall_FullMethodName = "/proto.Module/OnImcCall"
)

// ModuleClient is the client API for Module service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModuleClient interface {
	OnLoad(ctx context.Context, in *OnLoadRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	OnUnload(ctx context.Context, in *OnUnloadRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	OnMessage(ctx context.Context, in *OnMessageRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	OnImcCall(ctx context.Context, in *OnImcCallRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type moduleClient struct {
	cc grpc.ClientConnInterface
}

func NewModuleClient(cc grpc.ClientConnInterface) ModuleClient {
	return &moduleClient{cc}
}

func (c *moduleClient) OnLoad(ctx context.Context, in *OnLoadRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, Module_OnLoad_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleClient) OnUnload(ctx context.Context, in *OnUnloadRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, Module_OnUnload_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleClient) OnMessage(ctx context.Context, in *OnMessageRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, Module_OnMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleClient) OnImcCall(ctx context.Context, in *OnImcCallRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, Module_OnImcCall_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModuleServer is the server API for Module service.
// All implementations must embed UnimplementedModuleServer
// for forward compatibility
type ModuleServer interface {
	OnLoad(context.Context, *OnLoadRequest) (*EmptyResponse, error)
	OnUnload(context.Context, *OnUnloadRequest) (*EmptyResponse, error)
	OnMessage(context.Context, *OnMessageRequest) (*EmptyResponse, error)
	OnImcCall(context.Context, *OnImcCallRequest) (*EmptyResponse, error)
	mustEmbedUnimplementedModuleServer()
}

// UnimplementedModuleServer must be embedded to have forward compatible implementations.
type UnimplementedModuleServer struct {
}

func (UnimplementedModuleServer) OnLoad(context.Context, *OnLoadRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnLoad not implemented")
}
func (UnimplementedModuleServer) OnUnload(context.Context, *OnUnloadRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnUnload not implemented")
}
func (UnimplementedModuleServer) OnMessage(context.Context, *OnMessageRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnMessage not implemented")
}
func (UnimplementedModuleServer) OnImcCall(context.Context, *OnImcCallRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnImcCall not implemented")
}
func (UnimplementedModuleServer) mustEmbedUnimplementedModuleServer() {}

// UnsafeModuleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModuleServer will
// result in compilation errors.
type UnsafeModuleServer interface {
	mustEmbedUnimplementedModuleServer()
}

func RegisterModuleServer(s grpc.ServiceRegistrar, srv ModuleServer) {
	s.RegisterService(&Module_ServiceDesc, srv)
}

func _Module_OnLoad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnLoadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServer).OnLoad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Module_OnLoad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServer).OnLoad(ctx, req.(*OnLoadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Module_OnUnload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnUnloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServer).OnUnload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Module_OnUnload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServer).OnUnload(ctx, req.(*OnUnloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Module_OnMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServer).OnMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Module_OnMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServer).OnMessage(ctx, req.(*OnMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Module_OnImcCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnImcCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServer).OnImcCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Module_OnImcCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServer).OnImcCall(ctx, req.(*OnImcCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Module_ServiceDesc is the grpc.ServiceDesc for Module service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Module_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Module",
	HandlerType: (*ModuleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnLoad",
			Handler:    _Module_OnLoad_Handler,
		},
		{
			MethodName: "OnUnload",
			Handler:    _Module_OnUnload_Handler,
		},
		{
			MethodName: "OnMessage",
			Handler:    _Module_OnMessage_Handler,
		},
		{
			MethodName: "OnImcCall",
			Handler:    _Module_OnImcCall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "main.proto",
}
